vim.keymap.set("n", "<C-J>", "<C-W><C-J>")
vim.keymap.set("n", "<C-K>", "<C-W><C-K>")
vim.keymap.set("n", "<C-L>", "<C-W><C-L>")
vim.keymap.set("n", "<C-H>", "<C-W><C-H>")
vim.keymap.set("n", "<leader><space>", "<cmd>nohl<CR>")
vim.keymap.set("i", "jk", "<esc>")
-- vim.keymap.set("n", "-", vim.cmd.Ex)
vim.keymap.set("n", "<F5>", "<cmd>source $MYVIMRC<CR>")
vim.keymap.set("i", "<C-l>", "<c-g>u<Esc>[s1z=`]a<c-g>u")

vim.keymap.set("n", "]c", "j]czz")

vim.keymap.set("n", "<C-h>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateLeft()<cr>")
vim.keymap.set("n", "<C-j>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateDown()<cr>")
vim.keymap.set("n", "<C-k>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateUp()<cr>")
vim.keymap.set("n", "<C-l>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateRight()<cr>")
vim.keymap.set("n", "<C-\\>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateLastActive()<cr>")
vim.keymap.set("n", "<C-Space>", "<cmd>lua require'nvim-tmux-navigation'.NvimTmuxNavigateNext()<cr>")

vim.keymap.set("v", "<leader>be", "<cmd>lua require'b64'.encode()<cr>", { silent = true, noremap = true})
vim.keymap.set("n", "<leader>bd", "viW<cmd>lua require'b64'.decode()<cr>", { silent = true, noremap = true})

vim.keymap.set("n", "gC", function()
  require("treesitter-context").go_to_context(vim.v.count1)
end, { silent = true })

vim.keymap.set({ "n", "v" }, "<leader>F", function()
  require("conform").format({ async = true })
end, { desc = "Format buffer" })

vim.keymap.set({ "n", "v" }, "<leader>J", "<cmd>TSJToggle<cr>")

vim.keymap.set("n", "-", function() Snacks.explorer() end, { desc = "File Explorer" })
vim.keymap.set("n", "<leader>rr", function() Snacks.picker.registers() end, { desc = "Registers" })
vim.keymap.set("n", "<leader>fb", function() Snacks.picker.buffers() end, { desc = "File Explorer" })
vim.keymap.set("n", "<leader>ff", function() Snacks.picker.files() end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>fG", function() Snacks.picker.git_files() end, { desc = "Find Git Files" })
vim.keymap.set("n", "<leader>fr", function() Snacks.picker.recent() end, { desc = "Recent" })
vim.keymap.set("n", "<leader>fg", function() Snacks.picker.grep() end, { desc = "Grep" })
vim.keymap.set({ "n", "x" }, "<leader>fw", function() Snacks.picker.grep_word() end, { desc = "Visual selection or word" })
vim.keymap.set("n", "<leader>fh", function() Snacks.picker.help() end, { desc = "Help Pages" })
vim.keymap.set("n", "<leader>f/", function() Snacks.picker.search_history() end, { desc = "Search History" })
vim.keymap.set("n", "<leader>fs", function() Snacks.picker.lsp_symbols() end, { desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>fS", function() Snacks.picker.lsp_workspace_symbols() end, { desc = "LSP Workspace Symbols" })
vim.keymap.set("n", "<leader>fj", function() Snacks.picker.jumps() end, { desc = "Jumps" })
vim.keymap.set("n", "<leader>fd", function() Snacks.picker.diagnostics() end, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>fD", function() Snacks.picker.diagnostics_buffer() end, { desc = "Buffer Diagnostics" })
vim.keymap.set("n", "<leader>gb", function() Snacks.picker.git_branches() end, { desc = "Git Branches" })
vim.keymap.set("n", "<leader>gl", function() Snacks.picker.git_log() end, { desc = "Git Log" })
vim.keymap.set("n", "<leader>gL", function() Snacks.picker.git_log_line() end, { desc = "Git Log Line" })
vim.keymap.set("n", "<leader>gs", function() Snacks.picker.git_status() end, { desc = "Git Status" })
vim.keymap.set("n", "<leader>gS", function() Snacks.picker.git_stash() end, { desc = "Git Stash" })
vim.keymap.set("n", "<leader>gd", function() Snacks.picker.git_diff() end, { desc = "Git Diff (Hunks)" })
vim.keymap.set("n", "<leader>gf", function() Snacks.picker.git_log_file() end, { desc = "Git Log File" })
vim.keymap.set("n", "gd", function() Snacks.picker.lsp_definitions() end, { desc = "Goto Definition" })
vim.keymap.set("n", "gD", function() Snacks.picker.lsp_declaration() end, { desc = "Goto Definition" })
vim.keymap.set("n", "gr", function() Snacks.picker.lsp_references() end, { nowait = true, desc = "References" })
vim.keymap.set("n", "gi", function() Snacks.picker.lsp_implementations() end, { desc = "Goto Implementation" })
vim.keymap.set("n", "<leader>?", function() require("which-key").show({ global = false }) end)
