require("david.set") -- This must be set before lazy
require("david.lazy")
require("david.netrw")
require("david.keymap")
require("david.gitsigns")
require("david.indent")
require("david.debugger")
require("david.treesitter-context")
require("david.treesitter")
require("david.telescope")
